//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsCatalog.DDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ImageId { get; set; }
        public string FileName { get; set; }
        public int AdsId { get; set; }
        public string FileReference { get; set; }
    
        public virtual Ads Ads { get; set; }
    }
}
